### ISSUE TITLE
Data Process and Evaluation Code

### ISSUE THREAD

**Issue by haiahaiah** [Darshansingh11/AVLectures#4]
Thanks for your excellent work. I also want to know how to process data that has reached the input format required by the model.

In addition, the evaluation code of NMI, MOF, IOU, F1, BS@k was also not found.

It would be very nice if you could provide those information~

**Comment by Darshansingh11** [comment]
Hi,
Thank you for your interest in our work. I will release them by the end of this month since I am a bit busy right now because of a few deadlines.

**Comment by lucylqe** [comment]
Thank you for the update. I understand that you have a busy schedule with upcoming deadlines. Regarding your question about how the data is processed, could you please provide more specific information?

**Comment by Darshansingh11** [comment]
Hi, I have updated the readme with the necessary instructions to train and evaluate the model. Please check it. I am having issues with SharePoint, so I am not able to upload the pre-extracted features (they are around 11 GB) and model checkpoints. I will upload them soon and update here.
