### ISSUE TITLE
How to generate clips consistent with the splits_duration.pkl file and 9% of clips could not match the timestamp of any subtitle

### ISSUE THREAD

**Issue by haiahaiah** [Darshansingh11/AVLectures#5]
Hi, thanks for your excellent work. I have run the evaluation code on your model results [here](https://drive.google.com/drive/folders/1x3juCII1wrlAycOZoY40ba9Dm92Nt33K?usp=sharing). The obtained indicator results are consistent with those reported in the paper. 

But I found that the duration of each clip in file `Pickle_Files/splits_duration.pkl` is different from the duration I use `code/helpers/Split_Videos/driver.py`to generate. I tried two sets of time limits, 7-15 seconds and 10-15 seconds respectively, but I didn't get the same time distribution as in the duration file `Pickle_Files/splits_duration.pkl`.

In addition, I compared the timestamp of each clip in the duration `Pickle_Files/splits_duration.pkl`, and found that near 9% of the clips could not match the timestamp of any subtitle. So I hope you can tell me the source of the duration `Pickle_Files/splits_duration.pkl`, and the reason why some clips cannot match. Thank you~

**Comment by Darshansingh11** [comment]
Hi. It is because we remove the intro and outro of each lecture (we obtain the timestamps manually by watching the first and last few bits of the lecture). This will affect the split timestamp. You can check manually if the code gives proper 10s-15s splits for a few videos. It doesn't have to match with the pickle file provided.

**Comment by haiahaiah** [comment]
Okay, thanks. I found that your script `code/helpers/Split_Videos/driver.py` process the outermost subtitle files by default, which belong to the unprocessed videos. Therefore, there are many inconsistencies with the clip duration of the processed videos you provided. After I split the subtitle files of processed videos, the result is as expected. Thanks a lot!
